### ISSUE TITLE
Failure due to invalid flag to 6g - " unknown flag -asmhdr=/tmp/rsc-io-sizeof-..."

### ISSUE THREAD

**Issue by caelifer** [rsc/sizeof#1]
As of 68aefd8c06580f83b7f27b2eb5af5ea9582199d6, sizeof fails with this message on my Linux and MacOS X systems:

```
sizeof: # bytes
/opt/go/pkg/tool/linux_amd64/6g: unknown flag -asmhdr=/tmp/rsc-io-sizeof-598461128
```

Looks like `-asmhdr` flag is not supported by the installed `6g`.

I'm running this go version on both systems:

```
$ go version
go version go1.4.2 linux/amd64
```

Please, let me know if I can provide more information.

Thanks.

**Comment by caelifer** [comment]
Never mind. I just realize that this tool requires 1.5 toolchain. Closing this issue

**Comment by dmitshur** [comment]
> I just realize that this tool requires 1.5 toolchain.

Where does it say that? I don't see it in the README nor in the [godoc](https://godoc.org/rsc.io/sizeof) for the package.

When something doesn't support "latest stable version of Go", it's a good idea to mention that.
